repos:
  - repo: local
    hooks:

      ### CODE FORMATTING

      - id: black
        name: black
        stages: [ pre-commit ]
        language: system
        entry: uv
        args: [ run, black, . ]
        types: [ python ]

      ### CODE STYLE ENFORCEMENT

      - id: ruff
        name: ruff
        stages: [ pre-commit ]
        language: system
        entry: uv
        args: [ run, ruff, check, . ]
        types: [ python ]

      ### TYPE CHECKING

      - id: mypy
        name: mypy
        stages: [ pre-commit ]
        language: system
        entry: uv
        args: [ run, mypy, . ]
        types: [ python ]
        pass_filenames: false

      ### SECURITY

      # - id: check
      #   name: check
      #   stages: [ pre-push ]
      #   language: system
      #   entry: uv
      #   args: [ check ]
      #   types: [ python ]

      ### TESTING

      - id: pytest
        name: pytest
        stages: [ pre-push ]
        language: system
        entry: uv
        args: [ run, pytest ]
        types: [ python ]
        pass_filenames: false
